spring.application.name=LogiTrackBackendSystem

# SERVER
server.port=${PORT:8090}

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/logitrack?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# GMAIL SMTP

resend.api.key=${RESEND_API_KEY}

# JWT
app.jwtSecret=${APP_JWT_SECRET}
